# Parameters for BoxAL
# python boxal.py --config boxal.yaml
# explanation can be found here: https://github.com/pieterblok/boxal

# folders and files
weightsroot: "./weights"
resultsroot: "./results"
dataroot: "./datasets"
traindir: "./datasets/train"
valdir: "./datasets/val"
testdir: "./datasets/test"
sampledir: "./datasets/sample"
experiment_name: 'exp1'
csv: "uncertainty_estimates.csv"

# network parameters
network_config: "COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"
pretrained_weights: "COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"

# training-parameters
cuda_visible_devices: '0'
classes: ['healthy', 'damaged', 'matured', 'cateye', 'headrot']
learning_rate: 0.005
warmup_iterations: 500
train_iterations_base: 2500
train_iterations_step_size: 2500
step_image_number: 500
eval_period: 500
checkpoint_period: -1
weight_decay: 0.0001
learning_policy: 'steps_with_decay'
step_ratios: [0.5, 0.8]
gamma: 0.1
train_batch_size: 1
num_workers: 2

# train-sampler
train_sampler: "TrainingSampler"
minority_classes: ['damaged', 'matured', 'cateye', 'headrot']
repeat_factor_smallest_class: 1.0

# evaluation-parameters
confidence_threshold: 0.5
nms_threshold: 0.3

# sampling parameters
dropout_probability: 0.5
mcd_iterations: 30
iou_thres: 0.5
